name:                leap-relay
version:             0.1.0.0
github:              "githubuser/leap-relay"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/leap-relay#readme>

dependencies:
- base >= 4.7 && < 5
- vector

library:
  source-dirs: src

executables:
  leap-relay-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - leap-relay
    - Spock >=0.11
    - mtl
    - text
    - wai
    - wai-extra
    - stm
    - hleap
    - http-types
    - data-default
    - aeson
    - websockets
    - bytestring

tests:
  leap-relay-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - leap-relay
